/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as muddySol from "./Muddy.sol";
export type { muddySol };
import type * as muddyMinterSol from "./MuddyMinter.sol";
export type { muddyMinterSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { NFT } from "./NFT";
