/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20TokenSol from "./ERC20Token.sol";
export type { erc20TokenSol };
export type { Plots } from "./Plots";
export type { TouchGrass } from "./TouchGrass";
