/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20TokenSol from "./ERC20Token.sol";
export { Plots__factory } from "./Plots__factory";
export { TouchGrass__factory } from "./TouchGrass__factory";
