/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMuddyBurn,
  IMuddyBurnInterface,
} from "../../../contracts/MuddyMinter.sol/IMuddyBurn";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMuddyBurn__factory {
  static readonly abi = _abi;
  static createInterface(): IMuddyBurnInterface {
    return new Interface(_abi) as IMuddyBurnInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMuddyBurn {
    return new Contract(address, _abi, runner) as unknown as IMuddyBurn;
  }
}
